### ISSUE TITLE
isSuccessful does not exist

### ISSUE THREAD

**Issue by davoinb** [Orbitale/ImageMagickPHP#12]
The line:  if ($response->isSuccessful()) doesnt work. 
Use: if (!$response->hasFailed()) instead. 

And if you want to add some error messaging you can use: $response->getError()

please update the doc to save us some time. 

TY

**Comment by Pierstoval** [comment]
Can you make a pull-request to update the docs? It's just a simple `.md` file update 😉

**Comment by davoinb** [comment]
Done :)
