### ISSUE TITLE
read frames and check if file exist

### ISSUE THREAD

**Issue by davoinb** [Orbitale/ImageMagickPHP#14]
Hi, 
I have an issue with pdf files. 

If I want to create a thumbnail for only the first page of a pdf file, I need to add an index:
`myFile.pdf[0]`

But with $command->convert() the "checkExistingFile" function will throw an error:
'The file "myFile.pdf[0]" is not found.'."\n".
'If the file really exists in your filesystem, then maybe it is not readable.'

I fixed it for me by updating checkExistingFile , checking if there is an index at the end of the file name, and then used the file_exists function without it. 

Is there a syntaxe that could do the trick instead ? 

Ty :)

**Comment by Pierstoval** [comment]
Yep, you can now set the `$checkExistingFile` attribute to `false` with `->convert($sourceFile.'[0]', false)`.

Upgrade to `v2.0.2` to get the fix 😄 

⚠️  Be careful however, this version introduces a big BC Break in the `Command::text()` method.

**Comment by davoinb** [comment]
Nice ty  :)
