### ISSUE TITLE
Create 'auto-orient' command

### ISSUE THREAD

**Issue by viunyk** [Orbitale/ImageMagickPHP#15]
Hello, thanks for the package.
Could you please add '-auto-orient' command?
https://imagemagick.org/script/command-line-options.php#auto-orient

**Comment by Pierstoval** [comment]
Done in https://github.com/Orbitale/ImageMagickPHP/commit/167af5e53b461fbbefbfe899b319b631f7144988, and I just published `v3.0.8`.

Run `composer update orbitale/imagemagick-php` (maybe wait a few minutes for Packagist's cache to update) and you're set 😄
