### ISSUE TITLE
Rotate Function

### ISSUE THREAD

**Issue by prabhatjhaba** [Orbitale/ImageMagickPHP#2]

**Comment by prabhatjhaba** [comment]
Hi , In your Command.php you does not have rotate function , so please add function like this:-

```
public function rotate($geometry)
{
    $this->command .= ' -rotate '.$this->escape($this->ref->geometry($geometry));

    return $this;
}
```

, or let me know how to rotate image with this library

**Comment by Pierstoval** [comment]
Feel free to add a PR with the `rotate` method, else I can make it if you like :smile:

**Comment by Pierstoval** [comment]
Plus, the `rotate` command line option does not accept a `Geometry` argument, but a simple positive or negative number potentially followed by a `<` or a `>`, according to [ImageMagick's documentation](http://www.imagemagick.org/script/command-line-options.php#rotate)

**Comment by Pierstoval** [comment]
Closing: new `v1.4.1` release implements the option :smiley_cat:
