### ISSUE TITLE
Bug in blur

### ISSUE THREAD

**Issue by amk9978** [Orbitale/ImageMagickPHP#22]
Hi!
I think you have a typo in your blur code here:
`public function blur(string $blur): float`
You should change it from float to string, like this:
`public function blur(string $blur): string`
in Orbitale\Component\ImageMagick\Reference.php
That's it!
Otherwise it doesn't work properly and throws exception for something like this: 
**-blur 0x8**

**Comment by dimer47** [comment]
+1

**Comment by Pierstoval** [comment]
Fixed in 83914560495b0e911ea3d040d663e32c633868a2
