### ISSUE TITLE
Compatibility with PHP 8

### ISSUE THREAD

**Issue by pbories** [Orbitale/ImageMagickPHP#26]
Hey @Pierstoval, long time no see (thanks for your excellent Symfony lessons last year 😃) !

We are very interested in this library for our project but we are wondering : what is needed to make it compatible with PHP8 ?

**Comment by Pierstoval** [comment]
Oh, thanks for the compliment! We might talk about this in private if you like 😉 

For PHP8, I think executing the test suite on PHP8 as well as other versions, and maybe bumping dependencies versions might be a good start.

Are you up with a PR? 😉
