### ISSUE TITLE
-strip option not found

### ISSUE THREAD

**Issue by prabhatjhaba** [Orbitale/ImageMagickPHP#3]
Please add strip options , I need it to remove the meta info on images, Please include this option as I am stuck in middle of this.

When I tried to push the code it gives me 403 error, fatal: unable to access 'https://github.com/Orbitale/ImageMagickPHP.git/': The requested URL returned error: 403 .. Looks like I don't have permission to push the code to open the PR.

Thanks,
Prabhat

**Comment by Pierstoval** [comment]
@prabhatjhaba Make a fork of the repo if you want to make a pull request :)

**Comment by Pierstoval** [comment]
Closed by #4
