### ISSUE TITLE
Regex pattern for "rotation" command

### ISSUE THREAD

**Issue by jsedlmayr** [Orbitale/ImageMagickPHP#34]
The regex pattern check for the function `rotation()` in the file `References.php` is incorrect. 

It does not allow a single value, since it should be `~^-?\d+[<>]?$~u` instead of `~^-?\d+[<>]$~u` (note the `?` character after `[<>]`. Furthermore if the option `<` or `>` is set, the command also does not work, since the whole string has to be surrounded by `"`s to work correctly (which is not allowed by the regex pattern). 

I'd only need the single value option, so could you at least fix this as soon as possible, please?

**Comment by Pierstoval** [comment]
> I'd only need the single value option, so could you at least fix this as soon as possible, please?

Do you want to make a pull-request on this? You seem to have worked on it already 😉

**Comment by Pierstoval** [comment]
Fixed in [v3.1.1](https://github.com/Orbitale/ImageMagickPHP/releases/tag/v3.1.1)
