### ISSUE TITLE
Unable to set background Color

### ISSUE THREAD

**Issue by jchesne** [Orbitale/ImageMagickPHP#6]
Hi,

When i try this : 

```
$command->convert($imageSource)
            ->background("#121234")
            ->extent($width . 'x' . $height)
            ->file($imageSource)
            ->run();
```

I have folowed error : 
convert: missing an image filename `-background' @ error/convert.c/ConvertImageCommand/3259.

It's seems that the color must be in Quote or DoubleQuote because of the # caracter of the color.
When i try the exact same comand in terminal with color surrounded by quote everything work perfectly.

**Comment by Pierstoval** [comment]
Fixed in v1.6.1 [fba670f], thanks for the report 👍
