### ISSUE TITLE
Support multiimages output crop

### ISSUE THREAD

**Issue by Artusamak** [Orbitale/ImageMagickPHP#9]
Hi! Thanks for your lib. I hoped that i could have it working for my purpose.
I have an imagemap that i want to split into smaller images. I rely on the following imagemagick command: `convert source_map.png -crop 48x48 cropped_%d.png`

But if i translate it to your lib, it blows ^^

PHP Code
```
    $command = new Command();
    $response = $command
      ->convert('source_map.png')
      ->crop('48x48 cropped_%d.png')
      ->file('phpimage.png', false)
      ->run();
```

Error generated: `invalid argument for option '-crop': 48x48 cropped_%d.png @ error/convert.c/ConvertImageCommand/1184.`

Am i doing something wrong or is this just not supported?

(And just to be cautious, the next command that i would run would be `cropped_?.png -shave 5x5 cleaned_0%d.png` that would maybe require the same fix?)

Thanks!

**Comment by Artusamak** [comment]
I'm stupid, filename goes as the last parameter. So it doesn't generate the error anymore.

**Comment by Pierstoval** [comment]
Great, glad you found the issue!

Instead of using `->file(...)` as the last statement, you can also use `->output(...)` , it's an alias to `->file($source, false, true)` 😄
